# Generated by Django manually
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='accounts.customuser')),
                ('total_applications', models.IntegerField(default=0)),
                ('applications_this_month', models.IntegerField(default=0)),
                ('interview_rate', models.FloatField(default=0.0)),
                ('response_rate', models.FloatField(default=0.0)),
                ('offer_rate', models.FloatField(default=0.0)),
                ('rejection_rate', models.FloatField(default=0.0)),
                ('avg_days_to_response', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User Analytics',
            },
        ),
    ]
