# Generated by Django manually
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_emails', to='accounts.customuser')),
                ('gmail_message_id', models.CharField(max_length=255, unique=True)),
                ('thread_id', models.CharField(max_length=255)),
                ('sender', models.EmailField(max_length=254)),
                ('sender_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=1000)),
                ('received_at', models.DateTimeField()),
                ('snippet', models.TextField(blank=True, null=True)),
                ('is_job_related', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('detected_status', models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Assessment', 'Assessment'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Pending', 'Pending'), ('No Response', 'No Response'), ('Ghosted', 'Ghosted'), ('Unknown', 'Unknown')], max_length=50, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('application_confirmation', 'Application Confirmation'), ('application_received', 'Application Received'), ('interview_invitation', 'Interview Invitation'), ('assessment_invitation', 'Assessment Invitation'), ('recruiter_outreach', 'Recruiter Outreach'), ('rejection', 'Rejection'), ('offer', 'Offer'), ('next_round', 'Next Round'), ('hiring_manager_message', 'Hiring Manager Message'), ('coding_assessment', 'Coding Assessment'), ('interview_scheduling', 'Interview Scheduling'), ('application_status_update', 'Application Status Update'), ('position_filled', 'Position Filled'), ('candidate_not_selected', 'Candidate Not Selected'), ('application_withdrawn', 'Application Withdrawn'), ('other', 'Other')], max_length=50, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('processing_status', models.CharField(choices=[('detected', 'Detected'), ('needs_review', 'Needs Review'), ('ignored', 'Ignored'), ('processed', 'Processed'), ('failed', 'Failed')], default='detected', max_length=50)),
                ('application_id', models.IntegerField(blank=True, null=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [
                    models.Index(fields=['user', 'gmail_message_id'], name='processede_user_gmail_6b4a0e_idx'),
                    models.Index(fields=['user', 'thread_id'], name='processede_user_threa_2b3a1e_idx'),
                    models.Index(fields=['user', 'processing_status'], name='processede_user_proce_4b2a1c_idx'),
                    models.Index(fields=['user', 'is_job_related'], name='processede_user_is_job_8b1a2d_idx'),
                    models.Index(fields=['user', 'received_at'], name='processede_user_recei_2c3b4e_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=['user', 'gmail_message_id'], name='unique_user_message_id'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='accounts.customuser')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('emails_scanned', models.IntegerField(default=0)),
                ('job_related_emails', models.IntegerField(default=0)),
                ('applications_updated', models.IntegerField(default=0)),
                ('new_applications', models.IntegerField(default=0)),
                ('needs_review', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
