# Generated by Django 4.2.30 on 2026-08-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processedemail',
            new_name='gmail_integ_user_id_8b9eaf_idx',
            old_name='processede_user_gmail_6b4a0e_idx',
        ),
        migrations.RenameIndex(
            model_name='processedemail',
            new_name='gmail_integ_user_id_d0678d_idx',
            old_name='processede_user_threa_2b3a1e_idx',
        ),
        migrations.RenameIndex(
            model_name='processedemail',
            new_name='gmail_integ_user_id_14249e_idx',
            old_name='processede_user_proce_4b2a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='processedemail',
            new_name='gmail_integ_user_id_b7ee8b_idx',
            old_name='processede_user_is_job_8b1a2d_idx',
        ),
        migrations.RenameIndex(
            model_name='processedemail',
            new_name='gmail_integ_user_id_3e0cee_idx',
            old_name='processede_user_recei_2c3b4e_idx',
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='detected_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
