# Generated by Django 4.2.30 on 2026-08-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0002_rename_processede_user_gmail_6b4a0e_idx_gmail_integ_user_id_8b9eaf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='compressed_size_bytes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='r2_object_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='triage_priority',
            field=models.CharField(choices=[('P1', 'P1 - High (Interview/Offer)'), ('P2', 'P2 - Medium (Application/Status/Assessment)'), ('P3', 'P3 - Low (Newsletter/Rejection/Alerts)')], db_index=True, default='P2', max_length=10),
        ),
    ]
