# Generated by Django 4.2.30 on 2026-08-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0003_processedemail_compressed_size_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='r2_compression_version',
            field=models.CharField(default='gzip-v1', max_length=20),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='r2_content_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='r2_storage_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed'), ('pruned', 'Pruned (Retention Expired)')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='raw_retention_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='triage_priority',
            field=models.CharField(choices=[('P1', 'P1 - High (Interview/Offer/Decision/Rejection)'), ('P2', 'P2 - Medium (Assessment/Application/Status/Recruiter)'), ('P3', 'P3 - Low (Alerts/Newsletters/Deferred)')], db_index=True, default='P2', max_length=10),
        ),
    ]
