# Generated by Django 4.2.30 on 2026-08-31 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gmail_integration', '0004_processedemail_r2_compression_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(db_index=True, max_length=255)),
                ('thread_id', models.CharField(db_index=True, max_length=255)),
                ('priority', models.CharField(choices=[('P1', 'P1 - High (Interview/Offer/Decision/Rejection)'), ('P2', 'P2 - Medium (Assessment/Application/Status/Recruiter)'), ('P3', 'P3 - Low (Alerts/Newsletters/Deferred)')], db_index=True, default='P2', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('RETRY', 'Retry'), ('FAILED', 'Failed'), ('NEEDS_REVIEW', 'Needs Review'), ('DEAD_LETTER', 'Dead Letter')], db_index=True, default='PENDING', max_length=20)),
                ('triage_status', models.CharField(choices=[('job_likely', 'Job Likely'), ('uncertain', 'Uncertain'), ('low_priority', 'Low Priority')], db_index=True, default='uncertain', max_length=20)),
                ('triage_score', models.FloatField(default=0.0)),
                ('triage_reason', models.TextField(blank=True, null=True)),
                ('triaged_at', models.DateTimeField(auto_now_add=True)),
                ('processing_stage', models.CharField(default='triage', max_length=50)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('next_attempt_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('locked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('effective_priority_score', models.FloatField(db_index=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_job', to='gmail_integration.processedemail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'next_attempt_at'],
                'indexes': [models.Index(fields=['priority', 'status', 'next_attempt_at'], name='gmail_integ_priorit_fcc543_idx'), models.Index(fields=['thread_id', 'priority'], name='gmail_integ_thread__394a69_idx'), models.Index(fields=['status', 'locked_at'], name='gmail_integ_status_262158_idx')],
            },
        ),
    ]
