# Generated by Django 4.2.30 on 2026-08-31 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gmail_integration', '0005_emailprocessingjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('request_tokens', models.IntegerField(default=0)),
                ('response_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('status_code', models.IntegerField(default=200)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'created_at'], name='gmail_integ_provide_1ff8ab_idx'), models.Index(fields=['provider', 'success'], name='gmail_integ_provide_a8a6d2_idx')],
            },
        ),
    ]
