# Generated by Django 4.2.30 on 2026-09-05 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gmail_integration', '0006_providerusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('cursor', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.IntegerField(default=0)),
                ('pages_processed', models.IntegerField(default=0)),
                ('emails_fetched', models.IntegerField(default=0)),
                ('emails_stored', models.IntegerField(default=0)),
                ('emails_queued', models.IntegerField(default=0)),
                ('job_related_emails', models.IntegerField(default=0)),
                ('applications_updated', models.IntegerField(default=0)),
                ('new_applications', models.IntegerField(default=0)),
                ('needs_review', models.IntegerField(default=0)),
                ('worker_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lease_timeout_seconds', models.IntegerField(default=300)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='gmail_integ_user_id_ddcdd6_idx'), models.Index(fields=['status', 'last_heartbeat_at'], name='gmail_integ_status_1f3b3c_idx')],
            },
        ),
    ]
