# Generated by Django 4.2.30 on 2026-09-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0007_gmailsyncjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprocessingjob',
            name='sync_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_jobs', to='gmail_integration.gmailsyncjob'),
        ),
        migrations.AddIndex(
            model_name='emailprocessingjob',
            index=models.Index(fields=['sync_job', 'status'], name='gmail_integ_sync_jo_2e096c_idx'),
        ),
    ]
