# Generated by Django manually
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='accounts.customuser')),
                ('request_type', models.CharField(max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('response_time', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'created_at'], name='airequestl_user_creat_4b3a2e_idx'),
                    models.Index(fields=['user', 'request_type'], name='airequestl_user_reque_2b3a1e_idx'),
                ],
            },
        ),
    ]
