# Generated by Django 4.2.30 on 2026-08-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='airequestlog',
            new_name='ai_processi_user_id_d63297_idx',
            old_name='airequestl_user_creat_4b3a2e_idx',
        ),
        migrations.RenameIndex(
            model_name='airequestlog',
            new_name='ai_processi_user_id_c6758a_idx',
            old_name='airequestl_user_reque_2b3a1e_idx',
        ),
    ]
