# Generated by Django manually
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.customuser')),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Indeed', 'Indeed'), ('Company Website', 'Company Website'), ('Naukri', 'Naukri'), ('Wellfound', 'Wellfound'), ('Referral', 'Referral'), ('Email', 'Email'), ('Other', 'Other')], default='Other', max_length=50)),
                ('application_date', models.DateField()),
                ('current_status', models.CharField(choices=[('Applied', 'Applied'), ('Assessment', 'Assessment'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Pending', 'Pending'), ('No Response', 'No Response'), ('Ghosted', 'Ghosted'), ('Unknown', 'Unknown')], default='Applied', max_length=50)),
                ('status_updated_at', models.DateTimeField(auto_now_add=True)),
                ('last_email_date', models.DateTimeField(blank=True, null=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_ai_detected', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-application_date'],
                'indexes': [
                    models.Index(fields=['user', 'company'], name='applicatio_user_comp_2b4b0e_idx'),
                    models.Index(fields=['user', 'current_status'], name='applicatio_user_curr_4b3b2a_idx'),
                    models.Index(fields=['user', 'application_date'], name='applicatio_user_apply_8b3a2e_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='applications.application')),
                ('draft_subject', models.CharField(max_length=500)),
                ('draft_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('previous_status', models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Assessment', 'Assessment'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Pending', 'Pending'), ('No Response', 'No Response'), ('Ghosted', 'Ghosted'), ('Unknown', 'Unknown')], max_length=50, null=True)),
                ('new_status', models.CharField(choices=[('Applied', 'Applied'), ('Assessment', 'Assessment'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Pending', 'Pending'), ('No Response', 'No Response'), ('Ghosted', 'Ghosted'), ('Unknown', 'Unknown')], max_length=50)),
                ('source', models.CharField(default='ai', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_email_id', models.IntegerField(blank=True, null=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name_plural': 'Status Histories',
            },
        ),
    ]
