# Generated by Django 4.2.30 on 2026-08-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='application_user_id_e87bc1_idx',
            old_name='applicatio_user_comp_2b4b0e_idx',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='application_user_id_d961f7_idx',
            old_name='applicatio_user_curr_4b3b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='application_user_id_937080_idx',
            old_name='applicatio_user_apply_8b3a2e_idx',
        ),
    ]
