# Generated by Django 4.2.30 on 2026-08-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_applicatio_user_comp_2b4b0e_idx_application_user_id_e87bc1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='recruiter_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='recruiter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='review_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='days_stale',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='followup',
            name='suggested_send_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='current_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Assessment', 'Assessment'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('No Response', 'No Response'), ('Stale', 'Stale'), ('Ghosted', 'Ghosted'), ('Needs Review', 'Needs Review'), ('Unknown', 'Unknown')], default='Applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Assessment', 'Assessment'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('No Response', 'No Response'), ('Stale', 'Stale'), ('Ghosted', 'Ghosted'), ('Needs Review', 'Needs Review'), ('Unknown', 'Unknown')], max_length=50),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Assessment', 'Assessment'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('No Response', 'No Response'), ('Stale', 'Stale'), ('Ghosted', 'Ghosted'), ('Needs Review', 'Needs Review'), ('Unknown', 'Unknown')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'needs_review'], name='application_user_id_d3d839_idx'),
        ),
    ]
